version: '3.9'

services:
  rairnode:
    container_name: 'rairnode'
    build:
      context: rairnode/
      dockerfile: Dockerfile
    volumes:
      - ./rairnode/db:/usr/src/rairnode/db
    environment:
      PRODUCTION: "false"
      MONGO_URI:  mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      MONGO_URI_LOCAL: mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      GENERATE_MONGO_URI_WITH_VAULT_CREDENTIAL_UTIL: ${rairnode_generate_mongo_uri_with_vault_credential_util}
      USE_X509_CERT_AUTH: ${VAULT_RAIRNODE_use_x509_cert_auth}
      MONGO_DB_HOSTNAME: ${RAIRNODE_mongo_db_hostname}
      MONGO_DB_NAME: ${mongo_db_name}
      JWT_SECRET: ${jwt_secret}
      PINATA_KEY: ${pinata_key}
      PINATA_SECRET: ${pinata_secret}
      ADMIN_NETWORK: ${admin_nft_chain}
      ADMIN_CONTRACT: ${admin_contract}
      SUPER_ADMIN_VAULT_STORE: ${SUPER_ADMIN_VAULT_STORE}
      INFURA_PROJECT_ID: ${infura_project_id}
      SERVICE_HOST: ${hostname}
      DEFAULT_PRODUCT_COVER: ${default_product_cover}
      GCP_PROJECT_ID: ${gcp_project_id}
      GCP_IMAGE_BUCKET_NAME: ${gcp_image_bucket_name}
      GCP_VIDEO_BUCKET_NAME: ${gcp_video_bucket_name}
      GCP_GATEWAY: ${gcp_gateway}
      GCP_CREDENTIALS: ${gcp_credentials}
      IPFS_SERVICE: ${ipfs_service}
      IPFS_GATEWAY: ${ipfs_gateway}
      IPFS_API: ${ipfs_api}
      PINATA_GATEWAY: ${pinata_gateway}
      MATIC_TESTNET_RPC: ${matic_testnet_rpc}
      MATIC_MAINNET_RPC: ${matic_mainnet_rpc}
      BINANCE_MAINNET_RPC: ${binance_mainnet_rpc}
      BINANCE_TESTNET_RPC: ${binance_testnet_rpc}
      ETHEREUM_MAINNET_RPC: ${ethereum_mainnet_rpc}
      ETHEREUM_TESTNET_GOERLI_RPC: ${ethereum_testnet_goerli_rpc}
      MONGO_LOG_COLLECTION: ${mongo_log_collection}
      LOG_LEVEL: ${log_level}
      VAULT_URL: ${VAULT_URL}
      VAULT_RAIRNODE_APP_ROLE_ID: ${VAULT_RAIRNODE_APP_ROLE_ID}
      VAULT_RAIRNODE_APP_ROLE_SECRET_ID: ${VAULT_RAIRNODE_APP_ROLE_SECRET_ID}
      MORALIS_SERVER_TEST: ${moralis_server_test}
      MORALIS_SERVER_MAIN: ${moralis_server_main}
      MORALIS_API_KEY_TEST: ${moralis_api_key_test}
      MORALIS_API_KEY_MAIN: ${moralis_api_key_main}
      REDIS_HOST: ${redisthhost}
      REDIS_PORT: ${redisport}
      SESSION_SECRET: ${session_secret}
      SESSION_TTL: ${session_ttl}
      SENTRY_DSN: ${sentry_dsn}
      BASE_BCN_URL: ${base_bcn_url}
    ports:
      - 3000:3000
      - 5000:5000
    depends_on:
      - rair-redis
      - mongo
    networks:
      - rair-local
  blockchain-networks:
    container_name: 'blockchain-networks'
    build:
      context: blockchain-networks-service/
      dockerfile: Dockerfile
    environment:
      PRODUCTION: "false"
      MONGO_URI: mongodb+srv://${dbuser}:${dbpass}@${dbhost}
      MONGO_URI_LOCAL: mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      MONGO_DB_HOSTNAME: ${BLOCKCHAIN_NETWORK_mongo_db_hostname}
      MONGO_DB_NAME: ${mongo_db_name}
      GENERATE_MONGO_URI_WITH_VAULT_CREDENTIAL_UTIL: ${blockchain_network_generate_mongo_uri_with_vault_credential_util}
      USE_X509_CERT_AUTH: ${VAULT_BLOCKCHAIN_NETWORK_use_x509_cert_auth}
      PINATA_KEY: ${pinata_key}
      PINATA_SECRET: ${pinata_secret}
      PINATA_GATEWAY: ${pinata_gateway}
      INFURA_PROJECT_ID: ${infura_project_id}
      DEFAULT_PRODUCT_COVER: ${default_product_cover}
      BINANCE_TESTNET_FACTORY_ADDRESS: ${binance_testnet_factory_addres}
      BINANCE_TESTNET_MINTER_ADDRESS: ${binance_testnet_minter_address}
      BINANCE_MAINNET_FACTORY_ADDRESS: ${binance_mainnet_factory_addres}
      BINANCE_MAINNET_MINTER_ADDRESS: ${binance_mainnet_minter_address}
      GOERLI_FACTORY_ADDRESS: ${goerli_factory_addres}
      GOERLI_MINTER_ADDRESS: ${goerli_minter_address}
      GOERLI_RESALE_ADDRESS: ${goerli_resale_address}
      MATIC_MUMBAI_FACTORY_ADDRESS: ${matic_mumbai_factory_addres}
      MATIC_MUMBAI_MINTER_ADDRESS: ${matic_mumbai_minter_address}
      MATIC_MAINNET_FACTORY_ADDRESS: ${matic_mainnet_factory_addres}
      MATIC_MAINNET_MINTER_ADDRESS: ${matic_mainnet_minter_address}
      ETHEREUM_MAINNET_FACTORY_ADDRESS: ${ethereum_mainnet_factory_addres}
      ETHEREUM_MAINNET_MINTER_ADDRESS: ${ethereum_mainnet_minter_address}
      BINANCE_MAINNET_DIAMOND_FACTORY_ADDRESS: ${binance_mainnet_diamond_factory_address}
      BINANCE_MAINNET_DIAMOND_MARKETPLACE_ADDRESS: ${binance_mainnet_diamond_marketplace_address}
      BINANCE_TESTNET_DIAMOND_FACTORY_ADDRESS: ${binance_testnet_diamond_factory_address}
      BINANCE_TESTNET_DIAMOND_MARKETPLACE_ADDRESS: ${binance_testnet_diamond_marketplace_address}
      GOERLI_DIAMOND_FACTORY_ADDRESS: ${goerli_diamond_factory_address}
      GOERLI_DIAMOND_MARKETPLACE_ADDRESS: ${goerli_diamond_marketplace_address}
      MATIC_MUMBAI_DIAMOND_FACTORY_ADDRESS: ${matic_mumbai_diamond_factory_address}
      MATIC_MUMBAI_DIAMOND_MARKETPLACE_ADDRESS: ${matic_mumbai_diamond_marketplace_address}
      MATIC_MAINNET_DIAMOND_FACTORY_ADDRESS: ${matic_mainnet_diamond_factory_address}
      MATIC_MAINNET_DIAMOND_MARKETPLACE_ADDRESS: ${matic_mainnet_diamond_marketplace_address}
      BINANCE_RESALE_ADDRESS: ${binance_resale_address}
      MATIC_MUMBAI_RESALE_ADDRESS: ${matic_mumbai_resale_address}
      SYNC_CONTRACT_REPEAT_EVERY: ${sync_contract_repeat_every}
      SYNC_CONTRACT_TASK_INTERVAL: ${sync_contract_task_interval}
      IPFS_SERVICE: ${ipfs_service}
      IPFS_GATEWAY: ${ipfs_gateway}
      IPFS_API: ${ipfs_api}
      MONGO_LOG_COLLECTION: ${mongo_log_collection}
      LOG_LEVEL: ${log_level}
      VAULT_URL: ${VAULT_URL}
      VAULT_BLOCKCHAIN_NETWORK_APP_ROLE_ID: ${VAULT_BLOCKCHAIN_NETWORK_APP_ROLE_ID}
      VAULT_BLOCKCHAIN_NETWORK_APP_ROLE_SECRET_ID: ${VAULT_BLOCKCHAIN_NETWORK_APP_ROLE_SECRET_ID}
      TEST_BSCSCAN_GATEWAY: ${test_bscscan_gateway}
      TEST_POLYGONSCAN_GATEWAY: ${test_polygonscan_gateway}
      TEST_ETHERSCAN_GATEWAY: ${test_etherscan_gateway}
      POLYGONSCAN_GATEWAY: ${polygonscan_gateway}
      ETHERSCAN_GATEWAY: ${etherscan_gateway}
      BSCSCAN_GATEWAY: ${bscscan_gateway}
      MORALIS_SERVER_TEST: ${moralis_server_test}
      MORALIS_SERVER_MAIN: ${moralis_server_main}
      MORALIS_API_KEY_TEST: ${moralis_api_key_test}
      MORALIS_API_KEY_MAIN: ${moralis_api_key_main}
      MORALIS_MASTER_KEY_TEST: ${moralis_master_key_test}
      MORALIS_MASTER_KEY_MAIN: ${moralis_master_key_main}
      SENTRY_DSN: ${sentry_dsn}
      BASE_RAIRNODE_URL: ${base_rairnode_url}
      MATIC_TESTNET_RPC: ${matic_testnet_rpc}
      MATIC_MAINNET_RPC: ${matic_mainnet_rpc}
      BINANCE_MAINNET_RPC: ${binance_mainnet_rpc}
      BINANCE_TESTNET_RPC: ${binance_testnet_rpc}
      ETHEREUM_MAINNET_RPC: ${ethereum_mainnet_rpc}
      ETHEREUM_TESTNET_GOERLI_RPC: ${ethereum_testnet_goerli_rpc}
    ports:
      - 5001:5001
    depends_on:
      - rairnode
      - mongo
    networks:
      - rair-local
  media-service:
    container_name: 'media-service'
    build:
      context: media-service/
      dockerfile: Dockerfile
    environment:
      PRODUCTION: "false"
      MEDIA_SERVICE_PORT: ${media_service_port}
      BASE_RAIRNODE_URL: ${base_rairnode_url}
      GCP_PROJECT_ID: ${gcp_project_id}
      GCP_IMAGE_BUCKET_NAME: ${gcp_image_bucket_name}
      GCP_VIDEO_BUCKET_NAME: ${gcp_video_bucket_name}
      GCP_CREDENTIALS: ${gcp_credentials}
      GCP_GATEWAY: ${gcp_gateway}
      USE_X509_CERT_AUTH: ${VAULT_BLOCKCHAIN_NETWORK_use_x509_cert_auth}
      PINATA_KEY: ${pinata_key}
      PINATA_SECRET: ${pinata_secret}
      PINATA_GATEWAY: ${pinata_gateway}
      IPFS_SERVICE: ${ipfs_service}
      IPFS_GATEWAY: ${ipfs_gateway}
      IPFS_API: ${ipfs_api}
      MONGO_LOG_COLLECTION: ${mongo_log_collection}
      LOG_LEVEL: ${log_level}
      VAULT_URL: ${VAULT_URL}
      VAULT_RAIRNODE_APP_ROLE_ID: ${VAULT_RAIRNODE_APP_ROLE_ID}
      VAULT_RAIRNODE_APP_ROLE_SECRET_ID: ${VAULT_RAIRNODE_APP_ROLE_SECRET_ID}
      SENTRY_DSN: ${sentry_dsn}
    ports:
      - 5002:5002
    networks:
      - rair-local
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./rairnode/dev/db-data:/data/db
      - ./rairnode/dev/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${localdbuser}
      MONGO_INITDB_ROOT_PASSWORD: ${localdbpass}
      MONGO_INITDB_DATABASE: rair-db
    ports:
      - 27017:27017
    networks:
      - rair-local
  rair-redis:
    container_name: "rair-redis"
    image: redis
    command: redis-server --appendonly yes
    restart: always
    ports:
      - 6379:6379
    networks:
      - rair-local
  minting-network:
    container_name: minting-network
    build:
      context: minting-marketplace
      dockerfile: Dockerfile
    environment:
      REACT_APP_SENTRY_ENABLED: ${sentry_enabled}
      REACT_APP_SENTRY_IO_ENDPOINT: ${sentry_endpoint}
      REACT_APP_SENTRY_IO_TRACE_RATE: ${sentry_trace_rate}
      REACT_APP_SENTRY_RELEASE: ${sentry_release}
      REACT_APP_GOOGLE_ANALYTICS: ${react-app-google-analytics}
      REACT_APP_GA_NAME: ${react-app-ga-name}
      REACT_APP_DISABLE_CREATOR_VIEWS: ${react-app-disable-creator-views}
    ports:
      - 80:3001
    networks:
      - rair-local
networks:
  rair-local:
    driver: bridge
