version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: rair-nginx
    volumes:
      - ./nginx-auth/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-auth/error.log:/etc/nginx/error_log.log
      - ./nginx-auth/cache/:/etc/nginx/cache
      #Run certbot on the local server with proper hostname
      - /etc/letsencrypt/:/etc/letsencrypt/
      #- ./nginx-auth/auth/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    environment:
      - ENV=development
      - APPLICATION_URL=${hostname}
    networks:
      - rair-local
    depends_on:
      - minting-network
  rairnode:
    container_name: 'rairnode'
    image: rairtechinc/rairservernode:dev_latest
    volumes:
      - ./demo-decrypt-node/db:/usr/local/src/db
      - ./demo-decrypt-node/bin/Videos:/usr/local/src/bin/Videos
    restart: always
    environment:
      PRODUCTION: "true"
      MONGO_URI: mongodb+srv://${dbuser}:${dbpass}@${dbhost}
      MONGO_URI_LOCAL: mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      JWT_SECRET: ${jwt_secret}
      PINATA_KEY: ${pinata_key}
      PINATA_SECRET: ${pinata_secret}
      ADMIN_NETWORK: ${admin_nft_chain}
      ADMIN_CONTRACT: ${admin_contract}
      INFURA_PROJECT_ID: ${infura_project_id}
      SERVICE_HOST: ${hostname}
      DEFAULT_PRODUCT_COVER: ${default_product_cover}
      GCP_PROJECT_ID: ${gcp_project_id}
      GCP_IMAGE_BUCKET_NAME: ${gcp_image_bucket_name}
      GCP_VIDEO_BUCKET_NAME: ${gcp_video_bucket_name}
      GCP_GATEWAY: ${gcp_gateway}
      GCP_CREDENTIALS: ${gcp_credentials}
      IPFS_SERVICE: ${ipfs_service}
      IPFS_GATEWAY: ${ipfs_gateway}
      IPFS_API: ${ipfs_api}
      PINATA_GATEWAY: ${pinata_gateway}
      MATIC_TESTNET_RPC: ${matic_testnet_rpc}
      MATIC_MAINNET_RPC: ${matic_mainnet_rpc}
      BINANCE_MAINNET_RPC: ${binance_mainnet_rpc}
      BINANCE_TESTNET_RPC: ${binance_testnet_rpc}
      ETHEREUM_MAINNET_RPC: ${ethereum_mainnet_rpc}
      ETHEREUM_TESTNET_GOERLI_RPC: ${ethereum_testnet_goerli_rpc}
      MONGO_LOG_COLLECTION: ${mongo_log_collection}
      LOG_LEVEL: ${log_level}
      REDIS_HOST: ${redisthhost}
      REDIS_PORT: ${redisport}
      SESSION_SECRET: ${session_secret}
      SESSION_TTL: ${session_ttl}
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - rair-local
  rair-redis:
    container_name: "rair-redis"
    image: redis
    command: redis-server --appendonly yes
    restart: always
    ports:
      - 6379:6379
    networks:
      - rair-local

#  rairfront:
#    container_name: 'rairfront'
#    image: rairtechinc/rairfront:dev_latest
#    ports:
#      - 8080:80
#    networks:
#      - rair-local
#  mongo:
#    container_name: mongo
#   image: mongo
#   restart: always
#    volumes:
#      - ./demo-decrypt-node/dev/db-data:/data/db
#      - ./demo-decrypt-node/dev/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#   environment:
#      MONGO_INITDB_ROOT_USERNAME: ${localdbuser}
#      MONGO_INITDB_ROOT_PASSWORD: ${localdbpass}
#      MONGO_INITDB_DATABASE: rair-db
#    ports:
#      - 27017:27017
#    networks:
#      - rair-local
  minting-network:
    container_name: minting-network
    expose:
      - "80"
    image: rairtechinc/minting-network:dev_latest
    environment:
      REACT_APP_SENTRY_ENABLED: ${sentry_enabled}
      REACT_APP_SENTRY_IO_ENDPOINT: ${sentry_endpoint}
      REACT_APP_SENTRY_IO_TRACE_RATE: ${sentry_trace_rate}
      REACT_APP_SENTRY_RELEASE: ${sentry_release}
    ports:
      - 3001:3001
    networks:
      - rair-local
networks:
  rair-local:
    driver: bridge
