apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-event-listener-env
data:
  PRODUCTION: "true"
  PINATA_KEY: ${pinata_key}
  PINATA_GATEWAY: https://rair.mypinata.cloud/ipfs
  INFURA_PROJECT_ID: 92a88973a28d41318792f77451db4c5b
  DEFAULT_PRODUCT_COVER: https://rair.mypinata.cloud/ipfs/QmNtfjBAPYEFxXiHmY5kcPh9huzkwquHBcn9ZJHGe7hfaW
  BINANCE_TESTNET_FACTORY_ADDRES: "0x2b5ed3C018DA72270C3C30003C8d5affdBB9F7f5"
  BINANCE_TESTNET_MINTER_ADDRESS: "0xcBA6014452e82eBF98fA2748BBD46f1733a13AdD"
  BINANCE_TESTNET_DIAMOND_FACTORY_ADDRESS: "0xA2c57691b8DF0D8479f5f888c69346363D23a49F"
  BINANCE_TESTNET_DIAMOND_MARKETPLACE_ADDRESS: "0xaCb13B4c527eD6237f7DB6E95Ef71929d1e13DD6"
  GOERLI_FACTORY_ADDRES: "0xe1BBd1d2B2B52042CC3B766Fb72AA2804e402B2e"
  GOERLI_MINTER_ADDRESS: "0x14ef15A945b6Cae28f4FA3862E41d74E484Cd3B5"
  GOERLI_DIAMOND_FACTORY_ADDRESS: "0xEF85370b8F136E2F28eA904bF0dA5acac3D1d74f"
  GOERLI_DIAMOND_MARKETPLACE_ADDRESS: "0x6B3c06b39Aa1ADe73c625b184326d4837c7a2b64"
  MATIC_MUMBAI_FACTORY_ADDRES: "0x2E8DC5Bc8523Bd129dc770908b41c5c2c22d4AdD"
  MATIC_MUMBAI_MINTER_ADDRESS: "0x4594D508cDa05D016571082d467889f4629e1f56"
  MATIC_MUMBAI_DIAMOND_FACTORY_ADDRESS: "0xbB236Ce48dDCb58adB8665E220FE976bA5d080a5"
  MATIC_MUMBAI_DIAMOND_MARKETPLACE_ADDRESS: "0x2c8BA9f098CD319a971cE2705F26723c81044Cb0"
  MATIC_MAINNET_FACTORY_ADDRES: "0x701931758cB94F9AA684e13f710F5e4B85Bb94F2"
  MATIC_MAINNET_MINTER_ADDRESS: "0x781F15a23506CF28539EA057e3f33008E6339E49"
  MATIC_MAINNET_DIAMOND_FACTORY_ADDRESS: "0x9498b23e964760364435C23c793e9352Ff4E2200"
  MATIC_MAINNET_DIAMOND_MARKETPLACE_ADDRESS: "0x51eA5316F2A9062e1cAB3c498cCA2924A7AB03b1"
  ETHEREUM_MAINNET_FACTORY_ADDRESS: "0xC9eF9902fa24923A17326aDdb7da0E67fF46692a"
  ETHEREUM_MAINNET_MINTER_ADDRESS: "0x0Ce668D271b8016a785Bf146e58739F432300B12"
  SYNC_CONTRACT_REPEAT_EVERY: "5"
  SYNC_CONTRACT_TASK_INTERVAL: "5"
  MORALIS_SERVER_TEST: https://ldz2lkdhowt1.usemoralis.com:2053/server
  MORALIS_SERVER_MAIN: https://y14jhwis7uao.moralishost.com:2053/server
  MORALIS_API_KEY_TEST: 1fwzRnhKfABUG6v8PBgsQlRmbdKsgjLKqvmPMZEn
  MORALIS_MASTER_KEY_TEST: P3bQyDqkU5NU80xt2lTg3jGDaFP2KN0XkbtxpNV5